name: "Shellcheck"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Generate scripts
        run: make
      - name: Run shellcheck
        run: shellcheck --severity=info `find . -name "*.sh"`
