name: "Shellcheck"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Generate scripts
        run: make
      - name: Run shellcheck
        run: shellcheck --severity=info `find . -name "*.sh"`
